USE [DB_SYS_GREEN]
GO

/****** Object:  Table [dbo].[SYS_MENU]    Script Date: 08/17/2017 01:55:35 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SYS_MENU](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ThuTrongTuan] [nvarchar](50) NULL,
	[Create_User] [nvarchar](50) NULL,
	[Create_Date] [date] NULL,
 CONSTRAINT [PK_SYS_MENU] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

