USE [DB_SYS_GREEN]
GO

/****** Object:  Table [dbo].[SHIPER_NgayHoaDon]    Script Date: 7/29/2017 6:24:52 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SHIPER_NgayHoaDon](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SHIPER_ID] [int] NULL,
	[NgayHoaDon_ID] [int] NULL,
 CONSTRAINT [PK_SHIPER_NgayHoaDon] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[SHIPER_NgayHoaDon]  WITH CHECK ADD  CONSTRAINT [FK_SHIPER_NgayHoaDon_NgayHoaDon] FOREIGN KEY([NgayHoaDon_ID])
REFERENCES [dbo].[NgayHoaDon] ([ID])
GO

ALTER TABLE [dbo].[SHIPER_NgayHoaDon] CHECK CONSTRAINT [FK_SHIPER_NgayHoaDon_NgayHoaDon]
GO

ALTER TABLE [dbo].[SHIPER_NgayHoaDon]  WITH CHECK ADD  CONSTRAINT [FK_SHIPER_NgayHoaDon_SHIPER] FOREIGN KEY([SHIPER_ID])
REFERENCES [dbo].[SHIPER] ([SHIPER_ID])
GO

ALTER TABLE [dbo].[SHIPER_NgayHoaDon] CHECK CONSTRAINT [FK_SHIPER_NgayHoaDon_SHIPER]
GO


