USE [DB_SYS_GREEN]
GO

/****** Object:  Table [dbo].[SHIPER]    Script Date: 7/29/2017 6:21:10 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[SHIPER](
	[SHIPER_ID] [int] IDENTITY(1,1) NOT NULL,
	[NUMBER] [nvarchar](64) NULL,
	[NAME] [nvarchar](64) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
 CONSTRAINT [PK_SHIPER] PRIMARY KEY CLUSTERED 
(
	[SHIPER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO


